#!/usr/local/bin/ruby
# must be scheduled in crontab to run as the same user as oddb

$: << File.expand_path('../lib', File.dirname(__FILE__))
$: << File.expand_path('..', File.dirname(__FILE__))

require 'migel/util/job'
require 'migel/util/importer'

module Migel
  module Util
    Job.run do |system|
      Importer.new.save_all_products('data/csv/migel_product_de.csv', 'de', true)
      Importer.new.save_all_products('data/csv/migel_product_fr.csv', 'fr', true)
      Importer.new.import_all_products_from_csv(File.expand_path('../../data/csv/migel_product_de.csv', __FILE__), 'de', true)
      Importer.new.import_all_products_from_csv(File.expand_path('../../data/csv/migel_product_fr.csv', __FILE__), 'fr', true)
      system.init_fulltext_index_tables
    end
  end
end
